php update_lang.php admin student_load_error "We encountered an unexpected error while loading the students list. Please try again, or contact support if the problem persists." "حدث خطأ غير متوقع أثناء تحميل قائمة الطلاب. يرجى المحاولة مرة أخرى، أو الاتصال بالدعم إذا استمرت المشكلة."
php update_lang.php admin student_profile_error "We encountered an unexpected error while loading student profile. Please try again, or contact support if the problem persists." "حدث خطأ غير متوقع أثناء تحميل ملف تعريف الطالب. يرجى المحاولة مرة أخرى، أو الاتصال بالدعم إذا استمرت المشكلة."
php update_lang.php admin cannot_delete_admin "Cannot delete admin accounts." "لا يمكن حذف حسابات المشرفين."
php update_lang.php admin student_deleted "Student ':name' has been deleted." "تم حذف الطالب ':name'."
php update_lang.php admin student_delete_error "We encountered an unexpected error while deleting the student. Please try again, or contact support if the problem persists." "حدث خطأ غير متوقع أثناء حذف الطالب. يرجى المحاولة مرة أخرى، أو الاتصال بالدعم إذا استمرت المشكلة."
php update_lang.php admin cannot_ban_admin "Cannot ban admin accounts." "لا يمكن حظر حسابات المشرفين."
php update_lang.php admin student_status_changed "Student ':name' has been :status." "تمت :status للطالب ':name'."
php update_lang.php admin student_status_error "We encountered an unexpected error while updating the student status. Please try again, or contact support if the problem persists." "حدث خطأ غير متوقع أثناء تحديث حالة الطالب. يرجى المحاولة مرة أخرى، أو الاتصال بالدعم إذا استمرت المشكلة."
php update_lang.php admin cannot_reset_admin "Cannot reset admin passwords from here." "لا يمكن إعادة تعيين كلمات مرور المشرفين من هنا."
php update_lang.php admin student_password_reset "Password for ':name' has been reset successfully." "تم إعادة تعيين كلمة المرور لـ ':name' بنجاح."
php update_lang.php admin student_password_reset_error "We encountered an unexpected error while resetting the password. Please try again, or contact support if the problem persists." "حدث خطأ غير متوقع أثناء إعادة تعيين كلمة المرور. يرجى المحاولة مرة أخرى، أو الاتصال بالدعم إذا استمرت المشكلة."
